// index.js (ES Modules)
// Node / Express / EJS skeleton generated by ChatGPT

// --------------------
// Imports
// --------------------
import express from "express";
import path from "path";
import { fileURLToPath } from "url";

// --------------------
// __dirname replacement (ESM required)
// --------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --------------------
// App setup
// --------------------
const app = express();
const PORT = process.env.PORT || 3000;

// --------------------
// View engine setup
// --------------------
// Wasn't discussed in Udemy course (yet)
// app.set("view engine", "ejs");
// app.set("views", path.join(__dirname, "views"));

// --------------------
// Middleware
// --------------------

// Static files
app.use(express.static(path.join(__dirname, "public")));

// Body parsing (body-parser package no longer needed)
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// weekendChecker
var isWeekend = false;
function weekendChecker(req, res, next){ 
    console.log(req.body);
    var todate = new Date();
    var today = todate.getDay(); // should return 0-6
    if (today === 0 || today === 6) {
        isWeekend = true;
    }
    else {
        isWeekend = false;
    }
    next();
};

app.use(weekendChecker);

// --------------------
// App-wide locals
// --------------------
// app.locals.siteName = "My Express App";

// --------------------
// Routes
// --------------------

app.get("/", function (req, res) {
    if (isWeekend === false){
        res.render("index.ejs", {
        message: "Hey! It's a weekday, it's time to work hard!",
    });
    }
    else {
        res.render("index.ejs", {
        message: "Hey! It's the weekend, it's time to have fun!"
    });
    };    
});

// app.post("/submit", function (req, res) {
//   console.log(req.body);
//   res.redirect("/");
// });

// --------------------
// Start server
// --------------------
app.listen(PORT, function () {
  console.log("Server running on http://localhost:" + PORT);
});
